### ISSUE TITLE
Open Collaboard within nextcloud

### ISSUE THREAD

**Issue by dklueh79** [julien-nc/integration_collaboard#18]
Would be better to open  Collaboard within nextcloud, instead of clicking "open in a new tab"

**Comment by Wiggins2610** [comment]
Better would be to decide what I want. 
Sometimes it is better to work in another Tab. Sometimes not necessary. Just my opinion.

**Comment by jiayihu** [comment]
Fixed in https://github.com/nextcloud/integration_collaboard/pull/26.
- A new button "Open here" has been added to open the board in Nextcloud. Opening in a new tab is still possible
- In the Admin settings, a checkbox has been added to allow to open Collaboard links directly in Nextcloud, e.g. in Talk chats.
